spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:29092
            bindings:
                onlinePayments:
                    destination: online
                    contentType: application/json
                offlinePayments:
                    destination: offline
                    contentType: application/json
